# Site Settings
locale                   : "en"
title                    : Osaka Web Developers & Designers Meetup
email                    : ""
description              : "Osaka Web Developers & Designers Meetup"
baseurl                  : /owddm
url                      : https://coliff.github.io
repository               : "owddm/owddm.github.io"
bing_site_verification   : ""
future                   : false

comments:
  provider               : "staticman_v2"
staticman:
  branch                 : "master"

# Build settings
remote_theme             : mmistakes/minimal-mistakes

# Outputting
permalink                : /:categories/:title
paginate                 : 4
paginate_path            : /page:num/
timezone                 : Asia/Tokyo

social:
  name                   : "OWDDM"
  links:
    - "https://www.meetup.com/Osaka-Web-Designers-and-Developers-Meetup/"
    - "https://github.com/owddm"
    - "https://twitter.com/owddm"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jemoji

# Reading Files
include:
  - _pages
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - robots.txt

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      sitemap: false
  - scope:
      path: "assets/"
    values:
      sitemap: false
